[build]
  command = "yarn build:prod"
  publish = "_site"
  functions = "functions"

# Netlify subdomain
[[redirects]]
    from = "https://d-hagemeier.netlify.com/*"
    to = "https://www.d-hagemeier.com/:splat"
    status = 301
    force = true

# Old domain redirects
[[redirects]]
    from = "https://d-hagemeier.de/*"
    to = "https://www.d-hagemeier.com/"
    status = 301
    force = true

[[redirects]]
    from = "https://www.d-hagemeier.de/*"
    to = "https://www.d-hagemeier.com/"
    status = 301
    force = true

# Language redirects
[[redirects]]
  from = "/"
  to = "https://www.d-hagemeier.com/de/"
  status = 302
  force = true
  conditions = {Language = ["de,de-at,de-de,de-li,de-lu,de-ch"]}

[[redirects]]
  from = "/"
  to = "https://www.d-hagemeier.com/en/"
  status = 302
  force = true

# Preview images
[[redirects]]
  from = "/preview/:path"
  to = "https://preview.d-hagemeier.com/:path"
  status = 200

# 404
[[redirects]]
  from = "*"
  to = "/404"
  status = 404

# WP Login
[[redirects]]
  from = "/wp-login.php"
  to = "/404"
  status = 403

# HTTP Header
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Link = "</assets/css/main.css>; rel=preload; as=style,</assets/js/animate.js>; rel=preload; as=script,</assets/fonts/playfairdisplay-bold.woff2>; rel=preload; as=font; crossorigin,</assets/fonts/playfairdisplay-regular.woff2>; rel=preload; as=font; crossorigin"