[build]
  command = "yarn build"
  publish = "_site"

# Netlify subdomain
[[redirects]]
    from = "https://d-hagemeier.netlify.com/*"
    to = "https://www.d-hagemeier.com/:splat"
    status = 301
    force = true

# Old domain redirects
[[redirects]]
    from = "https://d-hagemeier.de/*"
    to = "https://www.d-hagemeier.com/"
    status = 301
    force = true

[[redirects]]
    from = "https://www.d-hagemeier.de/*"
    to = "https://www.d-hagemeier.com/"
    status = 301
    force = true

# Language redirects
[[redirects]]
  from = "/"
  to = "https://www.d-hagemeier.com/de/"
  status = 302
  force = true
  conditions = {Language = ["de,de-at,de-de,de-li,de-lu,de-ch"]}

[[redirects]]
  from = "/"
  to = "https://www.d-hagemeier.com/en/"
  status = 302
  force = true

# HTTP Header
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Link = "</assets/css/main.css>; rel=preload; as=style,</assets/js/animate.js>; rel=preload; as=script"